# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-26 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barrios',
        ),
    ]
