# Generated by Django 4.0.6 on 2022-08-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0004_rename_almacen_almacene_alter_donacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateField(blank=True)),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.donation')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='almacene',
            name='cod_producto',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='cod_producto',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='cod_donante',
        ),
        migrations.DeleteModel(
            name='Voluntario',
        ),
        migrations.DeleteModel(
            name='Almacene',
        ),
        migrations.DeleteModel(
            name='Donacion',
        ),
        migrations.DeleteModel(
            name='Donante',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='donation',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPLN.person'),
        ),
    ]
