# Generated by Django 4.0.6 on 2022-08-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0006_role_person_candidate_userpage_person_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='candidate',
            field=models.BooleanField(default=True),
        ),
    ]
