# Generated by Django 4.0.6 on 2022-09-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPLN', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_update',
        ),
    ]
